### ISSUE TITLE
Active area of the front page buttons is too small

### ISSUE THREAD

**Issue by dikonov** [Julien-Blanc-tgcm/kontroller#11]
The front page sports very large buttons with very small icons in their middle. It turns out that the buttons are just decorations. They cannot be pressed, unless your finger touches a very small active area with icon in the middle. This feels like a bug.
![frontpage_smallicons](https://user-images.githubusercontent.com/4271322/78270830-057b8c00-7514-11ea-8486-0d6e7461659b.jpg)
Some margin could be added at the bottom in landscape.

**Comment by Julien-Blanc-tgcm** [comment]
This was not obvious with a phone, thanks for pointing it. Fixed in v0.6
