### ISSUE TITLE
Music: Genre list is bogus

### ISSUE THREAD

**Issue by dikonov** [Julien-Blanc-tgcm/kontroller#12]
When I connect to my Kodi, I can successfully choose an album or an artist using the respective views. However, if I choose Genres menu, it opens a bogus list of many genres, including those not present in my collection. Each and every genre category is empty (contains nothing). Eg. Rock shows no rock albums, even though I personally tagged flac files with the Rock genre and scanned them with Kodi.

**Comment by Julien-Blanc-tgcm** [comment]
Fixed in 0.6

The list of genres is the one returned by Kodi, so there should be some data inside every one of them.
