### ISSUE TITLE
Music: No album covers in Artist view + GUI layout issues

### ISSUE THREAD

**Issue by dikonov** [Julien-Blanc-tgcm/kontroller#13]
When I choose browse music by artist AND enter a list of albums for a particular artist, I see the following:
![list_of_albums-no_covers](https://user-images.githubusercontent.com/4271322/78273147-1a0d5380-7517-11ea-9807-257eff0c5182.jpg)
The albums are shown without their graphical covers, which could provide a great visual clue. Those same albums have cover icons in Files and Album views. 

When I further choose an album, long song names may overlap the album cover. There is no wrapping around.
![list_of_songs-text_overlaps_cover](https://user-images.githubusercontent.com/4271322/78273484-8d16ca00-7517-11ea-9f6c-f51ed057003b.jpg)
Also Label:, and Genre: fields are empty. Note that Genre is filled in the respective file tags. This may be related with issue https://github.com/Julien-Blanc-tgcm/kontroller/issues/12

**Comment by Julien-Blanc-tgcm** [comment]
Genre not displayed should be fixed in 0.6.

The other issues are still valid. On a phone, there is no room for both the direct play buttons and the album cover, but i guess i can remove the "add to playlist" one, and implement it as a menu.

There is also a need for a "play album" button inside the album page.

**Comment by dikonov** [comment]
"Add to playlist" button is a good feature. It may be possible to check the screen size and show covers in landscape | on a tablet, where there is a lot of empty screen space.

**Comment by Julien-Blanc-tgcm** [comment]
Fixed in 0.9, closing it. Feel free to open a new issue if you still encounter issues with a tablet.
