### ISSUE TITLE
No volume control / no feedback

### ISSUE THREAD

**Issue by Julien-Blanc-tgcm** [Julien-Blanc-tgcm/kontroller#20]
Volume can be changed with physical buttons, but there is no feedback, and there is no way outside these buttons to change it.

A volume slider is needed.

**Comment by popanz** [comment]
I would ad that directly under the control buttons (play pause skip).

**Comment by Julien-Blanc-tgcm** [comment]
Fixed in 0.11. There is now both feedback and a volume slider.

There is room for improvement, though.
