### ISSUE TITLE
Issue 0.18-4

### ISSUE THREAD

**Issue by ghost** [Julien-Blanc-tgcm/kontroller#36]
Getting an error on starting the new version (screen stays white):
`
[W] unknown:85 - file:///usr/share/harbour-kontroller/qml/kontroller.qml:85:17: PlayerControl is not a type 
                     PlayerControl { 
                     ^
`

**Comment by Julien-Blanc-tgcm** [comment]
Thanks for reporting it. I broke up a qml file, it was not occurring on my device because the qml file was present. I just released version 0.18-6 which fixes this issue. Sorry for the inconvenience.
