### ISSUE TITLE
Wrong translation license?

### ISSUE THREAD

**Issue by comradekingu** [Julien-Blanc-tgcm/kontroller#37]
https://hosted.weblate.org/projects/kontroller/#information states LGPLv3+ when
https://github.com/Julien-Blanc-tgcm/kontroller/blob/master/LICENSE.md is GPLv3+.

"GNU General Public License 3 or later" can be selected in
https://hosted.weblate.org/settings/kontroller/kontroller
:)

I can help set it up the translation if you add https://hosted.weblate.org/user/kingu/ in https://hosted.weblate.org/access/kontroller/#users

Edit: The KODI Weblate is at https://kodi.weblate.cloud/ but there are some Kodi ones on Hosted too.

**Comment by Julien-Blanc-tgcm** [comment]
Fixed.
I've also given you access to the weblate interface. And thanks for the Norvegian translation !
