### ISSUE TITLE
Norwegian translation -> Make available as just nb ?

### ISSUE THREAD

**Issue by Julien-Blanc-tgcm** [Julien-Blanc-tgcm/kontroller#42]
The current Norwegian translation is only available as nb_NO locale. Does it make sense to make it available to all nb_* locales ? (I don't know enough of Norwegian culture to know if these people would prefer the English version over a Norwegian one…).

**Comment by comradekingu** [comment]
nb_NO is the correct one. nb shouldn't be used.
If you have an nn_NO install, you will have nb_NO as a fallback locale anyway.

As a further gotcha, there is also a shared "no" that should never be used either. :)

**Comment by Julien-Blanc-tgcm** [comment]
Ok, thanks for clarifying this!
