### ISSUE TITLE
Set up hooks for Weblate

### ISSUE THREAD

**Issue by comradekingu** [Julien-Blanc-tgcm/kontroller#45]
https://docs.weblate.org/no/latest/admin/continuous.html?highlight=webhooks#automatically-receiving-changes-from-github
And then it will surely be accepted for the libre plan.

**Comment by Julien-Blanc-tgcm** [comment]
Made that, and made the demand for the libre plan. Waiting for their answer now.

**Comment by Julien-Blanc-tgcm** [comment]
Has been accepted. Will add a note to suggest supporting weblate in the readme file.
